Fix minor typo in subscribe form
Gizra/og pull request #461
Opened 2019-01-12 21:05 UTC by jbrauer

Also issue [3014111](https://www.drupal.org/node/3014111) on d.o.

Should say "You are now subscribed" instead of "Your are now subscribed"

2019-01-13 02:20 UTC, MPParsley commented on src/Form/GroupSubscribeForm.php
> +    $message = $membership->isActive() ? $this->t('You are now subscribed to the group.') : $this->t('Your subscription request was sent.');
```suggestion
    $message = $membership->isActive() ? $this->t('You are now subscribed to the group.') : $this->t('Your subscription request has been sent.');
```

The message has (just) been sent. See https://english.stackexchange.com/questions/73143/simple-past-vs-present-perfect-was-vs-has-been

2019-01-13 02:24 UTC, MPParsley requested changes
Let's use the proper time.

2019-04-04 06:27 UTC, MPParsley approved these changes

2019-04-23 07:27 UTC, pfrenssen approved these changes

2019-04-23 07:28 UTC, merged