Add my groups overview
Gizra/og pull request #466
Opened 2019-03-12 12:07 UTC by MPParsley

See #426.

2019-04-23 13:05 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +use Drupal\og\OgRoleInterface;
```suggestion
```

2019-04-23 13:05 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +    $row['roles'] = implode(', ', array_map(function(OgRoleInterface $role) {return $role->getLabel();}, $entity->getRoles()));
```suggestion
    $callback = function(OgRoleInterface $role) {
      return $role->getLabel();
    }
    $row['roles'] = implode(', ', array_map($callback, $entity->getRoles()));
```

2019-06-21 09:12 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +    }
```suggestion
    };
```

2019-06-21 09:22 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +    $callback = function(OgRoleInterface $role) {
```suggestion
    $callback = function (OgRoleInterface $role) {
```

2019-06-21 09:23 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +  public function render() {
```suggestion
  /**
   * {@inheritdoc}
   */
  public function render() {
```

2019-06-21 09:26 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +   * @param array $a
```suggestion
   * @param array $a
   *   Group a.
```

2019-06-21 09:26 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +   * @param array $b
```suggestion
   * @param array $b
   *   Group b.
```

2019-06-21 09:27 UTC, MPParsley commented on src/OgMembershipListBuilder.php
> +   * @return int
```suggestion
   * @return int
   *   Returns the string comparison between the two labels of the groups.
```

2019-06-26 07:07 UTC, MPParsley commented on tests/src/Kernel/Entity/OgStandardReferenceItemTest.php
> +   * @var string[]
```suggestion
   * @var string
```

2019-09-02 13:53 UTC, matthijs-va requested changes

2019-09-02 13:53 UTC, matthijs-va commented on og.routing.yml
> +    _admin_route: 'TRUE'
This isn't an admin route.

2019-09-03 07:06 UTC, MPParsley commented on og.routing.yml
> +    _admin_route: 'TRUE'
```suggestion
```

2019-09-03 13:01 UTC, merged