472 Fixes
Gizra/og pull request #486
Opened 2019-05-02 13:50 UTC by MPParsley

2019-05-02 14:22 UTC, claudiu-cristea requested changes

2019-05-02 14:22 UTC, claudiu-cristea commented on og.module
>  function template_preprocess_og_member_count(array &$variables) {
We don't need the `template_preprocess_og_member_count()` anymore. We already have the `group_label` passed in the block plugin.

EDIT: And we should add the `group_label` also in the `hook_theme()` implementation.

2019-05-02 15:54 UTC, MPParsley commented on og.module
>  function template_preprocess_og_member_count(array &$variables) {
Indeed, I was going to remove the preprocess but forgot.
PS: you can add inline code suggestions, this makes reviews a lot easier.

2019-05-02 18:03 UTC, claudiu-cristea approved these changes

2019-05-08 09:06 UTC, pfrenssen approved these changes

2019-05-08 09:06 UTC, merged