Fixed documentation
Gizra/og pull request #498
Opened 2019-05-11 18:23 UTC by MPParsley

Fix #330: OgMembershipInterface::TYPE_DEFAULT

2019-05-12 12:21 UTC, pfrenssen requested changes
These changes are failing coding standards checks because they exceed 80 characters.

2019-05-12 12:21 UTC, pfrenssen commented on src/MembershipManagerInterface.php
> +   *   (optional) The membership type. Defaults to OgMembershipInterface::TYPE_DEFAULT.
```suggestion
   *   (optional) The membership type. Defaults to
       \Drupal\og\OgMembershipInterface::TYPE_DEFAULT.
```

2019-05-12 12:21 UTC, pfrenssen commented on src/Og.php
> +   *   (optional) The membership type. Defaults to OgMembershipInterface::TYPE_DEFAULT.
```suggestion
   *   (optional) The membership type. Defaults to
       \Drupal\og\OgMembershipInterface::TYPE_DEFAULT.
```

2019-05-12 13:31 UTC, MPParsley commented on src/MembershipManagerInterface.php
> +       \Drupal\og\OgMembershipInterface::TYPE_DEFAULT.
```suggestion
       * \Drupal\og\OgMembershipInterface::TYPE_DEFAULT.
```

2019-05-12 13:32 UTC, MPParsley commented on src/Og.php
> +       \Drupal\og\OgMembershipInterface::TYPE_DEFAULT.
```suggestion
   *   \Drupal\og\OgMembershipInterface::TYPE_DEFAULT.
```

2019-05-12 13:33 UTC, MPParsley commented
Thanks, the 80 characters limit should now pass.

2019-05-13 16:18 UTC, pfrenssen approved these changes

2019-05-13 16:18 UTC, merged