Removed unused variables
Gizra/og pull request #604
Opened 2019-12-24 14:22 UTC by kbrodej

Fix for #545

2020-01-06 09:03 UTC, MPParsley commented on src/ContextProvider/OgContext.php
> +        // $plugins[$plugin_id] = $plugin;
this doesn't seem right?

2020-01-06 12:10 UTC, kbrodej commented on src/ContextProvider/OgContext.php
> +        // $plugins[$plugin_id] = $plugin;
Fixed in the next commit.

2020-01-29 08:11 UTC, pfrenssen requested changes
Thanks for working on this! This is looking good, except for one case: PHP_CodeSniffer cannot understand the way that our test is using a variable assignment to trigger an exception. Instead of adding a fake line that returns the value, we should just disable this coding standards check for this case.

2020-01-29 08:11 UTC, pfrenssen commented on tests/src/Unit/PermissionEventTest.php
> +    return $event;
This should not be here, this test should not return any values. PHP_CodeSniffer cannot understand here that the variable is actually used in that it triggers an exception.

Let's add the following comments around it to disable this check:

```
    // Avoid false positive in coding standards checking. The variable is actually used for the test.
    // phpcs:disable DrupalPractice.CodeAnalysis.VariableAnalysis.UnusedVariable
    $event = new PermissionEvent($this->randomMachineName(), $this->randomMachineName(), []);
    $event[$key] = $permission;
    // phpcs:enable DrupalPractice.CodeAnalysis.VariableAnalysis.UnusedVariable
```

2020-01-29 10:10 UTC, pfrenssen approved these changes

2020-01-29 10:10 UTC, merged